name: waveform_recorder_example
description: "An example of the waveform_recorder package in action."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.6.0

environment:
  sdk: ^3.0.0

dependencies:
  audioplayers: any
  cross_file: ^0.3.4+2
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  gap: any
  waveform_flutter: ^1.2.0
  waveform_recorder:
    path: ../

dev_dependencies:
  all_lint_rules_community: ^0.0.41
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
