name: waveform_recorder
description: "A Flutter package for recording audio with real-time waveform visualization, ideal for voice messaging and audio recording features in chat applications."
version: 1.0.0
homepage: https://github.com/csells/waveform_recorder

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  http: ^1.2.2
  path: ^1.9.0
  path_provider: ^2.1.4
  record: ^5.1.2
  waveform_flutter: ^1.1.0

dev_dependencies:
  all_lint_rules_community: ^0.0.41
  flutter_test:
    sdk: flutter
